export enum ServiceType {
  HaircutforElder = "Soch olish kattalar uchun",
  HaircutforYoung = "Soch olish bolalar uchun (1-3 yosh)",
  HaircutforChildren = "Soch olish bolalar uchun (3-10 yosh)",
  HairStraightening = "Kantovka to'g'rilash",
  BeardTrim = "Soqol olish",
  HairWash = "Bosh yuvish",
  Combo = "Combo (soch olish + soqol olish + yuz chistkasi)",
  HairColoring = "Soch bo'yash",
  BeardColoring = "Soqol bo'yash",
  FaceMask = "Yuz niqobi",
  HairCurling = "Soch jingalak qilish",
  HairBalding = "Sochni kalga oldirish",
  HairStylingforBridgeGroom = "Soch olish (to'y uchun)",
}

export const ServicePrices: Record<ServiceType, number> = {
  [ServiceType.HaircutforElder]: 50000,
  [ServiceType.HaircutforChildren]: 40000,
  [ServiceType.HaircutforYoung]: 25000,
  [ServiceType.HairStraightening]: 30000,
  [ServiceType.BeardTrim]: 30000,
  [ServiceType.HairWash]: 30000,
  [ServiceType.Combo]: 100000,
  [ServiceType.HairColoring]: 40000,
  [ServiceType.BeardColoring]: 40000,
  [ServiceType.FaceMask]: 30000,
  [ServiceType.HairCurling]: 300000,
  [ServiceType.HairBalding]: 25000,
  [ServiceType.HairStylingforBridgeGroom]: 400000,
};
